services:
  desafiobancodigital.api:
    image: desafiobancodigital-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=aws-0-us-east-2.pooler.supabase.com;Port=5432;Database=postgres;Username=postgres.expuftdjveyaqxfhadnv;Password=190588;Ssl Mode=Require;Trust Server Certificate=true;
    networks:
      - banco-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "db.expuftdjveyaqxfhadnv.supabase.co:104.198.32.132"

networks:
  banco-network:
    driver: bridge
    enable_ipv6: false
