services:
  app:
    image: bancodigital-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db.ehmxvowmuyctkejiqvjo.supabase.co;Port=5432;Database=postgres;Username=postgres;Password=${DB_PASSWORD};Ssl Mode=Require;Trust Server Certificate=true

volumes:
  postgres-data:
